repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: "ml/_FINAL_SCRIPTS/"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0 # Use the same version as in requirements-dev.txt
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports, --exclude=ml/_FINAL_SCRIPTS] # Adjust args as needed
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        stages: [push] # Run pytest only on push, not every commit
        pass_filenames: false # pytest doesn't need filenames as arguments to run all tests
