"""Add ml_status and ml_job_id to TestSession and TestGroup

Revision ID: 1ca4fc21024a
Revises: acf87bf11a4a
Create Date: 2026-03-16 21:33:20.279776

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1ca4fc21024a"
down_revision = "acf87bf11a4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_groups", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ml_status", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("ml_job_id", sa.String(length=50), nullable=True))

    with op.batch_alter_table("test_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ml_status", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("ml_job_id", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_sessions", schema=None) as batch_op:
        batch_op.drop_column("ml_job_id")
        batch_op.drop_column("ml_status")

    with op.batch_alter_table("test_groups", schema=None) as batch_op:
        batch_op.drop_column("ml_job_id")
        batch_op.drop_column("ml_status")

    # ### end Alembic commands ###
