"""Add pd_probability and tremor_movements_json

Revision ID: 90d1a1c3d6a9
Revises: 
Create Date: 2025-12-11 23:48:38.674781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d1a1c3d6a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pd_probability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tremor_movements_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_column('tremor_movements_json')
        batch_op.drop_column('pd_probability')

    # ### end Alembic commands ###
