"""Add config column to test_sessions

Revision ID: 9cdf170d9090
Revises: 829038cfab8f
Create Date: 2026-02-09 18:37:46.150660

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9cdf170d9090"
down_revision = "829038cfab8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("config", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_sessions", schema=None) as batch_op:
        batch_op.drop_column("config")

    # ### end Alembic commands ###
