"""add test_groups table and group_id to test_sessions

Revision ID: acf87bf11a4a
Revises: a3f1b2c4d5e6
Create Date: 2026-03-15 06:50:27.631687

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "acf87bf11a4a"
down_revision = "a3f1b2c4d5e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_groups", schema=None) as batch_op:
        batch_op.create_index("idx_test_group_user_id", ["user_id"], unique=False)
        batch_op.create_index(
            "idx_test_group_user_status", ["user_id", "status"], unique=False
        )

    with op.batch_alter_table("esp32_devices", schema=None) as batch_op:
        batch_op.alter_column(
            "api_key", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.create_index("idx_esp32_api_key", ["api_key"], unique=False)
        batch_op.create_index(
            "idx_esp32_factory_api_key", ["factory_api_key"], unique=False
        )

    with op.batch_alter_table("test_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_test_sessions_group_id"), ["group_id"], unique=False
        )
        batch_op.create_foreign_key(None, "test_groups", ["group_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_sessions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_test_sessions_group_id"))
        batch_op.drop_column("group_id")

    with op.batch_alter_table("esp32_devices", schema=None) as batch_op:
        batch_op.drop_index("idx_esp32_factory_api_key")
        batch_op.drop_index("idx_esp32_api_key")
        batch_op.alter_column(
            "api_key", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    with op.batch_alter_table("test_groups", schema=None) as batch_op:
        batch_op.drop_index("idx_test_group_user_status")
        batch_op.drop_index("idx_test_group_user_id")

    op.drop_table("test_groups")
    # ### end Alembic commands ###
