"""add esp32_logs

Revision ID: c8a5747b3857
Revises: b4e12eb8a653
Create Date: 2026-05-09 20:17:08.507778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a5747b3857'
down_revision = 'b4e12eb8a653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esp32_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['esp32_devices.device_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('esp32_logs', schema=None) as batch_op:
        batch_op.create_index('idx_esp32_log_device_time', ['device_id', 'uploaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_esp32_logs_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esp32_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esp32_logs_device_id'))
        batch_op.drop_index('idx_esp32_log_device_time')

    op.drop_table('esp32_logs')
    # ### end Alembic commands ###
