name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          debug: true
          script: |
            whoami
            pwd
            ls -la
            cd PD-Server
            git pull origin main
            cd docker
            docker-compose build --parallel
            docker-compose up -d
            docker-compose ps
